// src/Client.Angular/src/app/account/components/reset-password-form/reset-password-form.component.ts

import { Component, inject, signal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../auth/services/auth.service';
import { extractApiErrors } from 'aufy-client/src/axios-utils';

@Component({
  selector: 'reset-password-form',
  templateUrl: './reset-password-form.component.html',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
})
export class ResetPasswordFormComponent {
  private fb = inject(FormBuilder);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private authService = inject(AuthService);

  resetForm: FormGroup;
  apiErrors = signal<string[] | undefined>(undefined);
  isSubmitting = signal(false);
  code: string;

  constructor() {
    this.code = this.route.snapshot.queryParamMap.get('code') ?? '';
    if (!this.code) {
      throw new Error('Invalid code');
    }

    this.resetForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required]
    }, { validators: this.passwordMatchValidator });
  }

  onSubmit(): void {
    if (this.resetForm.valid && !this.isSubmitting()) {
      this.isSubmitting.set(true);
      this.apiErrors.set(undefined);

      const { email, password } = this.resetForm.value;
      this.authService.aufy().resetPassword({ email, password, code: this.code }).then(() => {
          this.router.navigate(['/reset-password/confirmation']);
        }).catch((error) => {
          this.apiErrors.set(extractApiErrors(error) ?? ['An error occurred']);
          this.isSubmitting.set(false);
        });
    }
  }

  passwordMatchValidator(group: FormGroup): { [key: string]: any } | null {
    const password = group.get('password')?.value;
    const confirmPassword = group.get('confirmPassword')?.value;
    return password === confirmPassword ? null : { passwordMismatch: true };
  }
}

<form [formGroup]="resetForm" (ngSubmit)="onSubmit()" class="space-y-5" novalidate>
    @if (apiErrors()) {
      <div class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="ml-3">
            <div class="mt-2 text-sm text-red-700">
              <ul role="list" class="list-disc space-y-1 pl-5">
                @for (error of apiErrors(); track error) {
                  <li>{{ error }}</li>
                }
              </ul>
            </div>
          </div>
        </div>
      </div>
    }
  
    <div>
      <label for="email" class="block text-sm font-medium leading-6 text-gray-900">
        Email address
      </label>
      <div class="mt-2">
        <input
          formControlName="email"
          type="email"
          id="email"
          autocomplete="email"
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
        />
      </div>
      @if (resetForm.get('email')?.invalid && resetForm.get('email')?.touched) {
        <p class="mt-2 text-sm text-red-600">
          {{ resetForm.get('email')?.hasError('required') ? 'Email is required' : 'Must be a valid email' }}
        </p>
      }
    </div>
  
    <div>
      <label for="password" class="block text-sm font-medium leading-6 text-gray-900">
        Password
      </label>
      <div class="mt-2">
        <input
          formControlName="password"
          type="password"
          id="password"
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
        />
      </div>
      @if (resetForm.get('password')?.invalid && resetForm.get('password')?.touched) {
        <p class="mt-2 text-sm text-red-600">
          {{ resetForm.get('password')?.hasError('required') ? 'Password is required' : 'Password must be at least 6 characters' }}
        </p>
      }
    </div>
  
    <div>
      <label for="confirmPassword" class="block text-sm font-medium leading-6 text-gray-900">
        Confirm Password
      </label>
      <div class="mt-2">
        <input
          formControlName="confirmPassword"
          type="password"
          id="confirmPassword"
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
        />
      </div>
      @if (resetForm.hasError('passwordMismatch') && resetForm.get('confirmPassword')?.touched) {
        <p class="mt-2 text-sm text-red-600">
          Passwords don't match
        </p>
      }
    </div>
  
    <div>
      <button
        type="submit"
        [disabled]="resetForm.invalid || isSubmitting()"
        class="flex w-full justify-center rounded-md hover:primary-bg primary-bg px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
      >
        {{ isSubmitting() ? "Processing..." : "Reset Password" }}
      </button>
    </div>
  </form>

// src/Client.Vue/src/components/account/ResetPasswordForm.vue
﻿<template>
    <form @submit.prevent="handleSubmit" class="space-y-5" method="POST" novalidate>
        <div v-if="apiErrors" class="rounded-md bg-red-50 p-4">
            <div class="flex">
                <div class="ml-3">
                    <div class="mt-2 text-sm text-red-700">
                        <ul role="list" class="list-disc space-y-1 pl-5">
                            <li v-for="(error, index) in apiErrors" :key="index">{{ error }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <label for="email" class="block text-sm font-medium leading-6 text-gray-900">
                Email address
            </label>
            <div class="mt-2">
                <input
                    v-model="form.email"
                    type="email"
                    autocomplete="email"
                    class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
                />
            </div>
            <p class="mt-2 text-sm text-red-600"
               v-if="formErrors?.email?._errors">{{ formErrors?.email?._errors[0] }}</p>
        </div>

        <div>
            <label for="password" class="block text-sm font-medium leading-6 text-gray-900">
                Password
            </label>
            <div class="mt-2">
                <input
                    v-model="form.password"
                    type="password"
                    required
                    class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
                />
            </div>
            <p class="mt-2 text-sm text-red-600"
               v-if="formErrors?.password?._errors">{{ formErrors?.password?._errors[0] }}</p>
        </div>

        <div>
            <label for="confirmPassword" class="block text-sm font-medium leading-6 text-gray-900">
                Confirm Password
            </label>
            <div class="mt-2">
                <input
                    v-model="form.confirmPassword"
                    type="password"
                    required
                    class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
                />
            </div>
            <p class="mt-2 text-sm text-red-600"
                v-if="formErrors?.confirmPassword?._errors">{{ formErrors?.confirmPassword?._errors[0] }}</p>
        </div>

        <div>
            <button
                type="submit"
                class="flex w-full justify-center rounded-md hover:primary-bg primary-bg px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                :disabled="isSubmitting"
            >
                {{ isSubmitting ? 'Processing...' : 'Reset Password' }}
            </button>
        </div>
    </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { z } from 'zod';
import { extractApiErrors } from 'aufy-client/src/axios-utils';
import { useAuth } from '@/stores/AuthStore';

const apiErrors = ref<string[] | null>(null);
const form = ref({
    email: '',
    password: '',
    confirmPassword: '',
});

const isSubmitting = ref(false);
const router = useRouter();
const route = useRoute();
const { aufy } = useAuth();

const formSchema = z.object({
    email: z.string().min(1, { message: 'Email is required' }).email({ message: 'Must be a valid email' }),
    password: z.string().min(6, { message: 'Password must be at least 6 characters' }),
    confirmPassword: z.string().min(1, { message: 'Confirm Password is required' }),
}).refine((data) => data.password === data.confirmPassword, {
    path: ['confirmPassword'],
    message: 'Passwords don\'t match',
});
type formSchemaType = z.infer<typeof formSchema>;
const formErrors = ref<z.ZodFormattedError<formSchemaType> | null>(null);

const handleSubmit = async () => {
    isSubmitting.value = true;
    const validSchema = formSchema.safeParse(form.value);
    if (!validSchema.success) {
        formErrors.value = validSchema.error.format();
        isSubmitting.value = false;
        return;
    } else {
        formErrors.value = null;
    }

    try {
        const code = route.query.code;
        if (!code) {
            apiErrors.value = ['Invalid reset code'];
        }

        await aufy.resetPassword({ email: form.value.email, password: form.value.password, code: code as string });
        await router.push('/reset-password/confirmation');
    } catch (error) {
        apiErrors.value = extractApiErrors(error) ?? ['Error occurred'];
    } finally {
        isSubmitting.value = false;
    }
};
</script>
