// src/Client.Vue/src/components/auth/SignInForm.vue
﻿<template>
    <form class="space-y-6" action="#" method="POST" @submit.prevent="handleSubmit(onSubmit)" novalidate>
        <div v-if="apiErrors" class="rounded-md bg-red-50 p-4">
            <div class="flex">
                <div class="ml-3">
                    <div class="mt-2 text-sm text-red-700">
                        <ul role="list" class="list-disc space-y-1 pl-5">
                            <li v-for="(error, index) in apiErrors" :key="index">{{ error }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email address</label>
            <div class="mt-2">
                <input
                    v-model="form.email"
                    type="email"
                    autocomplete="email"
                    required
                    class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
                />
            </div>
            <p class="mt-2 text-sm text-red-600" id="email-error">{{ errors.email?.message }}</p>
        </div>

        <div>
            <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
            <div class="mt-2">
                <input
                    v-model="form.password"
                    type="password"
                    autocomplete="current-password"
                    required
                    class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
                />
            </div>
            <p class="mt-2 text-sm text-red-600" id="password-error">{{ errors.password?.message }}</p>
        </div>

        <div class="flex items-center justify-between">
            <div class="flex items-center"></div>
            <div class="text-sm leading-6">
                <RouterLink to="/forgot-password"
                            class="font-semibold primary-color hover:primary-color">Forgot password?</RouterLink>
            </div>
        </div>

        <div>
            <button
                type="submit"
                class="flex w-full justify-center rounded-md primary-bg px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:primary-bg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:primary-bg-darker"
                :disabled="isSubmitting"
            >
                {{ isSubmitting ? "Signing in..." : "Sign in" }}
            </button>
        </div>

        <div class="flex items-center justify-between">
            <div class="text-sm leading-6">
                Not a member?
                <RouterLink to="/signup"
                            class="ml-3 font-semibold primary-color hover:primary-color">Sign up now</RouterLink>
            </div>
        </div>
    </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { extractApiErrors } from 'aufy-client/src/axios-utils';
import { useAuth } from '@/stores/AuthStore';

// const validationSchema = z.object({
//     email: z.string().min(1, { message: "Email is required" }).email({ message: "Must be a valid email" }),
//     password: z.string().min(1, { message: "Password is required" }),
// });
//
// type FormModel = z.infer<typeof validationSchema>;
//
// const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormModel>({
//     resolver: zodResolver(validationSchema),
// });

const apiErrors = ref<string[] | undefined>(undefined);
const form = ref({ email: '', password: '' });
const { aufy } = useAuth();

const onSubmit = async (data: FormModel) => {
    try {
        await aufy.signIn({ email: data.email, password: data.password });
        navigate('/');
    } catch (error) {
        apiErrors.value = extractApiErrors(error) ?? ["Error occurred"];
    }
};
</script>

// src/Client.Angular/src/app/auth/components/signin-form/signin-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import {extractApiErrors} from "aufy-client/src/axios-utils";

@Component({
  selector: 'signin-form',
  templateUrl: './signin-form.component.html',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
  ],
})
export class SignInFormComponent {
  form: FormGroup;
  isSubmitting = false;
  apiErrors: string[] | undefined;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]]
    });
  }

  async onSubmit() {
    if (this.form.invalid) {
      return;
    }

    this.isSubmitting = true;
    this.apiErrors = undefined;

    try {
      await this.authService.aufy().signIn(this.form.value);
      await this.router.navigate(['/']);
    } catch (error) {
      this.apiErrors = this.extractApiErrors(error) ?? ['Error occurred'];
    } finally {
      this.isSubmitting = false;
    }
  }
}

<form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-6" novalidate>
    @if (apiErrors) {
      <div class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="ml-3">
            <div class="mt-2 text-sm text-red-700">
              <ul role="list" class="list-disc space-y-1 pl-5">
                @for (error of apiErrors; track error) {
                  <li>{{ error }}</li>
                }
              </ul>
            </div>
          </div>
        </div>
      </div>
    }
  
    <div>
      <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email address</label>
      <div class="mt-2">
        <input
          formControlName="email"
          id="email"
          type="email"
          autocomplete="email"
          required
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
        />
      </div>
      @if (form.get('email')?.invalid && form.get('email')?.touched) {
        <p class="mt-2 text-sm text-red-600">
          {{ form.get('email')?.hasError('required') ? 'Email is required' : 'Must be a valid email' }}
        </p>
      }
    </div>
  
    <div>
      <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
      <div class="mt-2">
        <input
          formControlName="password"
          id="password"
          type="password"
          autocomplete="current-password"
          required
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-inset focus:ring-black sm:text-sm sm:leading-6"
        />
      </div>
      @if (form.get('password')?.invalid && form.get('password')?.touched) {
        <p class="mt-2 text-sm text-red-600">
          Password is required
        </p>
      }
    </div>
  
    <div class="flex items-center justify-between">
      <div class="flex items-center"></div>
      <div class="text-sm leading-6">
        <a routerLink="/forgot-password" class="font-semibold primary-color hover:primary-color">Forgot password?</a>
      </div>
    </div>
  
    <div>
      <button
        type="submit"
        [disabled]="isSubmitting"
        class="flex w-full justify-center rounded-md primary-bg px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:primary-bg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:primary-bg-darker"
      >
        {{ isSubmitting ? 'Signing in...' : 'Sign in' }}
      </button>
    </div>
  
    <div class="flex items-center justify-between">
      <div class="text-sm leading-6">
        Not a member?
        <a routerLink="/signup" class="ml-3 font-semibold primary-color hover:primary-color">Sign up now</a>
      </div>
    </div>
  </form>
